# Configuración local de semgrep para facturacion_mexico
# Deshabilitamos reglas que generan falsos positivos en nuestro contexto específico

rules:
  # Deshabilitar regla que detecta falsamente métodos llamados desde on_update()
  # Estos métodos modifican campos en memoria y Frappe hace commit automáticamente
  - id: frappe-modifying-but-not-comitting-other-method
    enabled: false
    # Razón: sync_facturapi_history() y calculate_fiscal_status_from_logs() 
    # son llamados desde on_update() y el framework maneja el commit automáticamente